const DISPLAY_LABEL = {
  "zh-TW": {
    ipa: "IPA",
    kk: "KK",
    zhuyin_plus: "專利注音",
  },
  en: {
    ipa: "IPA",
    kk: "KK",
    zhuyin_plus: "Improved Zhuyin",
  },
};

const DEFAULT_DISPLAY_TABLE = {
  "p": { ipa: "p", symbol_id: "001", kk: "p", zhuyin_plus: "ㄆ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄆ\"" },
  "b": { ipa: "b", symbol_id: "002", kk: "b", zhuyin_plus: "ㄅ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄅ\"" },
  "t": { ipa: "t", symbol_id: "003", kk: "t", zhuyin_plus: "ㄊ(摩)", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄊ\"" },
  "d": { ipa: "d", symbol_id: "004", kk: "d", zhuyin_plus: "ㄉ(摩)", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄉ\"" },
  "k": { ipa: "k", symbol_id: "005", kk: "k", zhuyin_plus: "ㄎ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄎ\"" },
  "ɡ": { ipa: "ɡ", symbol_id: "006", kk: "ɡ", zhuyin_plus: "ㄍ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄍ\"" },
  "f": { ipa: "f", symbol_id: "007", kk: "f", zhuyin_plus: "ㄈ(f)", zhuyin_plus_C1: "ㄈ", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄈ(f)" },
  "v": { ipa: "v", symbol_id: "008", kk: "v", zhuyin_plus: "ㄈ(v)", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "θ": { ipa: "θ", symbol_id: "009", kk: "θ", zhuyin_plus: "ㄙ(θ)", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ð": { ipa: "ð", symbol_id: "010", kk: "ð", zhuyin_plus: "Z(θ)", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "s": { ipa: "s", symbol_id: "011", kk: "s", zhuyin_plus: "ㄙ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "z": { ipa: "z", symbol_id: "012", kk: "z", zhuyin_plus: "z", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ʃ": { ipa: "ʃ", symbol_id: "013", kk: "ʃ", zhuyin_plus: "*ㄒ*", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄒㄩ" },
  "ʒ": { ipa: "ʒ", symbol_id: "014", kk: "ʒ", zhuyin_plus: "ʒ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "h": { ipa: "h", symbol_id: "015", kk: "h", zhuyin_plus: "ㄏ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "tʃ": { ipa: "tʃ", symbol_id: "016", kk: "tʃ", zhuyin_plus: "*ㄑ*", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄑㄩ" },
  "dʒ": { ipa: "dʒ", symbol_id: "017", kk: "dʒ", zhuyin_plus: "*ㄐ*", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄐㄩ" },
  "m": { ipa: "m", symbol_id: "018", kk: "m", zhuyin_plus: "ㄇ", zhuyin_plus_C1: "ㄇ", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄇ~" },
  "n": { ipa: "n", symbol_id: "019", kk: "n", zhuyin_plus: "ㄋ", zhuyin_plus_C1: "ㄋ", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄋ~" },
  "ŋ": { ipa: "ŋ", symbol_id: "020", kk: "ŋ", zhuyin_plus: "ㄥ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "l": { ipa: "l", symbol_id: "021", kk: "l", zhuyin_plus: "ㄌ(黏)", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ɹ": { ipa: "ɹ", symbol_id: "022", kk: "ɹ", zhuyin_plus: "ㄖㄨ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "r": { ipa: "r", symbol_id: "023", kk: "r", zhuyin_plus: "ㄖㄨ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "j": { ipa: "j", symbol_id: "024", kk: "j", zhuyin_plus: "ㄧ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "w": { ipa: "w", symbol_id: "025", kk: "w", zhuyin_plus: "ㄨ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ɾ": { ipa: "ɾ", symbol_id: "026", kk: "ɾ", zhuyin_plus: "ㄌ(彈)", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ʔ": { ipa: "ʔ", symbol_id: "027", kk: "ʔ", zhuyin_plus: "ʔ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "i": { ipa: "i", symbol_id: "028", kk: "i", zhuyin_plus: "ㄧ(微)", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "iː": { ipa: "iː", symbol_id: "029", kk: "iː", zhuyin_plus: "ㄧ(微)", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ɪ": { ipa: "ɪ", symbol_id: "030", kk: "ɪ", zhuyin_plus: "ㄧㄜ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "eɪ": { ipa: "eɪ", symbol_id: "031", kk: "eɪ", zhuyin_plus: "ㄝㄧ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ɛ": { ipa: "ɛ", symbol_id: "032", kk: "ɛ", zhuyin_plus: "ㄝ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "æ": { ipa: "æ", symbol_id: "033", kk: "æ", zhuyin_plus: "ㄝㄚ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ɑ": { ipa: "ɑ", symbol_id: "034", kk: "ɑ", zhuyin_plus: "ㄚ(喉)", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ɑː": { ipa: "ɑː", symbol_id: "035", kk: "ɑː", zhuyin_plus: "ㄚ(喉)", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ɔ": { ipa: "ɔ", symbol_id: "036", kk: "ɔ", zhuyin_plus: "ㄚ(喉)", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ɔː": { ipa: "ɔː", symbol_id: "037", kk: "ɔː", zhuyin_plus: "ㄚ(喉)", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ʊ": { ipa: "ʊ", symbol_id: "038", kk: "ʊ", zhuyin_plus: "ㄨㄜ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "u": { ipa: "u", symbol_id: "039", kk: "u", zhuyin_plus: "ㄨ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "uː": { ipa: "uː", symbol_id: "040", kk: "uː", zhuyin_plus: "ㄨ(丹)", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ʌ": { ipa: "ʌ", symbol_id: "041", kk: "ʌ", zhuyin_plus: "ㄜ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ə": { ipa: "ə", symbol_id: "042", kk: "ə", zhuyin_plus: "ㄜ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ɚ": { ipa: "ɚ", symbol_id: "043", kk: "ɚ", zhuyin_plus: "ㄦ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ɝ": { ipa: "ɝ", symbol_id: "044", kk: "ɝ", zhuyin_plus: "ㄦ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ɜː": { ipa: "ɜː", symbol_id: "045", kk: "ɜː", zhuyin_plus: "ㄦ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "oʊ": { ipa: "oʊ", symbol_id: "046", kk: "oʊ", zhuyin_plus: "ㄜㄨ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "aɪ": { ipa: "aɪ", symbol_id: "047", kk: "aɪ", zhuyin_plus: "ㄞ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "aʊ": { ipa: "aʊ", symbol_id: "048", kk: "aʊ", zhuyin_plus: "ㄝㄠ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ɔɪ": { ipa: "ɔɪ", symbol_id: "049", kk: "ɔɪ", zhuyin_plus: "ㄛㄧ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ɐ": { ipa: "ɐ", symbol_id: "050", kk: "ɐ", zhuyin_plus: "ㄜ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ᵻ": { ipa: "ᵻ", symbol_id: "051", kk: "ᵻ", zhuyin_plus: "ㄧ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ʉ": { ipa: "ʉ", symbol_id: "052", kk: "ʉ", zhuyin_plus: "ㄧㄨ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ɑːɹ": { ipa: "ɑːɹ", symbol_id: "053", kk: "ɑːɹ", zhuyin_plus: "ㄚㄦ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ɔːɹ": { ipa: "ɔːɹ", symbol_id: "054", kk: "ɔːɹ", zhuyin_plus: "ㄛㄦ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ɪɹ": { ipa: "ɪɹ", symbol_id: "055", kk: "ɪɹ", zhuyin_plus: "ㄧㄦ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "əl": { ipa: "əl", symbol_id: "056", kk: "əl", zhuyin_plus: "ㄛ", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "a": { ipa: "a", symbol_id: "057", kk: "a", zhuyin_plus: "ㄚ(喉)", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "" },
  "ɲ": { ipa: "ɲ", symbol_id: "058", kk: "ɲ", zhuyin_plus: "ㄋ~", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄋ~" },
  "p̚": { ipa: "p̚", symbol_id: "059", kk: "p̚", zhuyin_plus: "ㄆ\"", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄆ\"" },
  "t̚": { ipa: "t̚", symbol_id: "060", kk: "t̚", zhuyin_plus: "ㄊ\"", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄊ\"" },
  "k̚": { ipa: "k̚", symbol_id: "061", kk: "k̚", zhuyin_plus: "ㄎ\"", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄎ\"" },
  "b̚": { ipa: "b̚", symbol_id: "062", kk: "b̚", zhuyin_plus: "ㄅ\"", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄅ\"" },
  "d̚": { ipa: "d̚", symbol_id: "063", kk: "d̚", zhuyin_plus: "ㄉ\"", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄉ\"" },
  "ɡ̚": { ipa: "ɡ̚", symbol_id: "064", kk: "ɡ̚", zhuyin_plus: "ㄍ\"", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄍ\"" },
  "b̥̚": { ipa: "b̥̚", symbol_id: "065", kk: "b̥̚", zhuyin_plus: "ㄅ\"", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄅ\"" },
  "d̥̚": { ipa: "d̥̚", symbol_id: "066", kk: "d̥̚", zhuyin_plus: "ㄉ\"", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄉ\"" },
  "ɡ̊̚": { ipa: "ɡ̊̚", symbol_id: "067", kk: "ɡ̊̚", zhuyin_plus: "ㄍ\"", zhuyin_plus_C1: "", zhuyin_plus_V: "", zhuyin_plus_C2: "ㄍ\"" },
  "ㄣ": { ipa: "ㄣ", symbol_id: "071", kk: "ㄣ", zhuyin_plus: "ㄣ", zhuyin_plus_C1: "", zhuyin_plus_V: "ㄣ", zhuyin_plus_C2: "" },
};

const DEFAULT_DISPLAY_EXCEPTIONS_PAYLOAD = {
  version: "1.0",
  description: "Word+IPA specific overrides for improved zhuyin display.",
  word_ipa_overrides: [
    {
      word_norm: "he'll",
      ipa: ["h", "i", "l"],
      zhuyin_plus: ["ㄏ", "ㄧ(微)", "ㄛ"],
    },
    {
      word_norm: "hell",
      ipa: ["h", "ɛ", "l"],
      zhuyin_plus: ["ㄏ", "ㄝ", "ㄛ"],
    },
    {
      word_norm: "ear",
      ipa: ["i", "ɹ"],
      zhuyin_plus: ["ㄧㄦ", ""],
    },
  ],
};

const RULE_LABELS = {
  s_cluster_stop_voicing_hint: {
    "zh-TW": "s+清塞音教學近似濁化",
    en: "s-cluster stop voiced-like hint",
  },
  final_stop_unreleased: { "zh-TW": "尾塞音不爆破", en: "final stop unreleased" },
  final_voiced_stop_devoiced_unreleased: {
    "zh-TW": "尾濁塞音清化且不爆破",
    en: "final voiced stop devoiced unreleased",
  },
  final_t_glottalization: { "zh-TW": "尾 t 喉塞化", en: "final t glottalization" },
  base_surface: { "zh-TW": "基礎表層音", en: "base surface" },
};

const FEATURE_LABELS = {
  coda_stop: { "zh-TW": "尾塞音", en: "coda stop" },
  coda_nasal: { "zh-TW": "尾鼻音", en: "coda nasal" },
  coda_unreleased: { "zh-TW": "尾音不爆破", en: "coda unreleased" },
  unreleased: { "zh-TW": "不爆破", en: "unreleased" },
  devoiced: { "zh-TW": "清化", en: "devoiced" },
  glottal_stop: { "zh-TW": "喉塞音", en: "glottal stop" },
  position_onset: { "zh-TW": "字首/音節首", en: "onset" },
  position_nucleus: { "zh-TW": "母音核心", en: "nucleus" },
  position_intervocalic: { "zh-TW": "母音間", en: "intervocalic" },
  position_coda: { "zh-TW": "尾音", en: "coda" },
  syllable_C1: { "zh-TW": "音節頭 C1", en: "syllable onset C1" },
  syllable_V: { "zh-TW": "音節核 V", en: "syllable nucleus V" },
  syllable_C2: { "zh-TW": "音節尾 C2", en: "syllable coda C2" },
};

const TAG_LABELS = {
  profile_recommended: { "zh-TW": "此風格推薦", en: "profile recommended" },
  saved_default: { "zh-TW": "目前預設", en: "saved default" },
};

const I18N = {
  "zh-TW": {
    appTitle: "跟讀小助手",
    loadingLesson: "載入課程中...",
    languageLabel: "介面語言",
    lessonSelectLabel: "課程",
    localLessonLabel: "本機課程（離線）",
    localLessonHint: "選取包含 lesson.json 與 sentences/ 的資料夾。",
    localLessonIdle: "可在此載入本機 lesson 資料夾，不需帳號或上傳。",
    localLessonAwaitImport: "請先載入本機 lesson 資料夾。",
    localLessonLoaded: (name, count) => `已載入本機課程：${name}（${count} 句）`,
    localLessonLoadFailed: (msg) => `本機課程載入失敗：${msg}`,
    localLessonNoFiles: "未選取任何檔案。",
    localLessonNoLessonJson: "找不到 lesson.json，請選取單一 run 資料夾。",
    localLessonMultipleLessonJson: "找到多個 lesson.json，請只選取單一 run 資料夾。",
    localLessonTooManyFiles: (n) => `檔案數過多（>${n}），請縮小資料夾範圍。`,
    localLessonTooLarge: (gb) => `資料夾總大小超過 ${gb} GB，請縮小資料夾範圍。`,
    localLessonServerUnavailable: (msg) => `伺服器模式不可用（${msg}），可改用本機課程載入。`,
    sentenceLabel: "句子",
    prev: "上一句",
    next: "下一句",
    displaySystemLabel: "顯示系統",
    loopSentence: "句子自動循環播放",
    loopGapLabel: "循環間隔（秒）",
    loopCountLabel: "循環次數（總播放，留白=無限）",
    audioOffsetLabel: "句子播放區間微調",
    audioOffsetHelp: (limit) => `每句可調整起訖偏移（秒），範圍 ±${limit} 秒。`,
    audioStartOffset: "起點偏移",
    audioEndOffset: "終點偏移",
    audioOffsetMinus: (step) => `-${step} 秒`,
    audioOffsetPlus: (step) => `+${step} 秒`,
    audioOffsetReset: "重設偏移",
    audioEffectiveRange: (start, end) => `實際播放範圍：${start} - ${end}`,
    viewModeLabel: "句子顯示模式",
    compactView: "精簡",
    detailedView: "詳細",
    presentationView: "展示",
    presentationReturn: "返回精簡",
    presentationPlay: "播放",
    presentationPause: "暫停",
    presentationPlayAll: "播放全部",
    presentationStopAll: "停止全部",
    presentationPlayAllHint: "連續播放全部句子",
    presentationStopAllHint: "停止連續播放",
    presentationPhonemeLabel: (label) => `音標（${label}）`,
    presentationDisplayHint: "顯示模式：切換音標系統",
    presentationLoopHintOn: "循環播放：開啟",
    presentationLoopHintOff: "循環播放：關閉",
    presentationGapHint: "播放間隔（秒）",
    presentationCountHint: "播放次數（留白=無限）",
    presentationSpeedHint: (rateText) => `播放速度：${rateText}（快捷鍵 [ / ]）`,
    presentationPhonemeToggleOn: "音標開",
    presentationPhonemeToggleOff: "音標關",
    presentationPhonemeToggleOnHint: "隱藏音標（快捷鍵 P）",
    presentationPhonemeToggleOffHint: "顯示音標（快捷鍵 P）",
    presentationPrevHint: "上一句",
    presentationNextHint: "下一句",
    downloadLessonJson: "下載 lesson JSON",
    downloadOfflineZip: "下載離線包（ZIP）",
    compactNoticeIdle: "精簡版可編輯顯示內容；請下載課程檔保存，未下載前關閉頁面會遺失。",
    compactNoticeUnsaved: "精簡版修改尚未下載；請先下載課程檔，否則關閉頁面後會遺失。",
    compactNoticeDownloaded: "精簡版修改已下載。",
    compactSavedInBrowser: "精簡版修改僅保存在瀏覽器，目前不會寫回伺服器 lesson。",
    compactDownloadFailed: (msg) => `下載失敗：${msg}`,
    compactSwitchLessonConfirm: "精簡版修改尚未下載，切換課程會遺失。確定切換？",
    keyboardLabel: "音標小鍵盤",
    keyboardHelp: "點選符號插入目前 Gold 欄位。",
    keyboardNoFocus: "請先點選一個 Gold 欄位。",
    phoneticProfileLabel: "發音細節風格",
    applyProfileSentence: "套用風格到本句",
    transcriptLabel: "文字稿（每行一句）",
    saveTranscript: "儲存文字稿",
    buildCommand: "產生重建指令",
    rebuildCommandIdle: "重建指令尚未產生。",
    rebuildCommandLoading: "重建指令產生中...",
    rebuildCommandReady: (outDir) => `重建指令已產生，將輸出到：${outDir}`,
    rebuildCommandFailed: (msg) => `重建指令產生失敗：${msg}`,
    rebuildCommandNeedSaveTranscript: "請先儲存文字稿，再產生重建指令。",
    rebuildCommandLocalUnavailable: "本機模式不提供重建指令。",
    transcriptLoading: "文字稿載入中...",
    transcriptUnavailable: "文字稿不可用。",
    transcriptReady: (n) => `文字稿已載入，共 ${n} 行。`,
    transcriptSaved: (path) => `文字稿已儲存：${path}`,
    transcriptSavedWithBackup: (path, backup) => `文字稿已儲存：${path}（備份：${backup}）`,
    transcriptNeedRebuild: "提示：文字稿已更新，但目前 lesson 尚未重建。",
    transcriptSaveFailed: (msg) => `文字稿儲存失敗：${msg}`,
    transcriptLocalUnavailable: "本機模式不提供文字稿寫回；請下載離線包保存編輯。",
    transcriptSourcePath: (path) => `來源：${path}`,
    transcriptSavePath: (path) => `儲存：${path}`,
    transcriptContentFromLesson: "目前內容來源：lesson 句子文字（首次建立）。",
    transcriptContentFromSource: "目前內容來源：原始/既有文字稿檔案。",
    transcriptUnsaved: "文字稿有未儲存變更。",
    switchLessonTranscriptConfirm: "文字稿有未儲存變更，切換課程會遺失。確定切換？",
    showDetails: "顯示詳細說明",
    nonIpaGoldEdited: "非 IPA 顯示模式的 Gold 修改僅保留於本機，可下載 lesson 保存。",
    nonIpaGoldSaveSkipped: "已儲存 IPA Gold；非 IPA 顯示模式修改僅保留在下載檔。",
    saveGoldEdits: "儲存 Gold 編輯",
    noUnsaved: "目前沒有未儲存變更。",
    quickFillLabel: "快速帶入",
    quickFillPlaceholder: "選擇帶入來源...",
    quickFillObserved: "辨識音標",
    quickFillTeaching: "教學候選",
    quickFillBestSurface: "最佳表層候選",
    quickFillCanonical: "Canonical",
    quickFillPhonetic: (n) => `發音細節候選 ${n}`,
    quickFillSurface: (n) => `表層候選 ${n}`,
    sentenceTitle: "句子",
    wordHeader: "單字",
    goldHeader: "Gold IPA（可編輯）",
    compactGoldHeader: (label) => `Gold（${label}，可編輯）`,
    notesHeader: "註記",
    noSentenceFilter: "目前篩選下沒有句子",
    noSentence: "沒有句子",
    noSentenceMessage: "目前篩選條件下沒有可顯示的句子。",
    rangeText: (start, end) => `範圍：${start} - ${end}`,
    alignmentText: (pct) => `對齊分數：${pct}%`,
    displayText: (label, text) => `${label}：${text}`,
    unsavedChanges: "有未儲存變更。",
    profileAppliedChanged: (n, sid) => `已套用風格：${sid} 更新 ${n} 個單字（尚未儲存）`,
    profileAppliedNoChange: (sid) => `已套用風格：${sid} 無需更新`,
    savedWithBackup: (backup) => `已儲存。備份：${backup}`,
    localSavedByDownload: "本機模式：請下載離線包保存編輯。",
    localSavedDownloaded: "本機模式：已下載 lesson JSON。",
    localSavedDownloadedZip: (n) => `本機模式：已下載離線包（含 ${n} 個音檔）。`,
    savedDownloadedZip: (n) => `已下載離線包（含 ${n} 個音檔）。`,
    savedDownloadedZipWithMissing: (n, missing) => `已下載離線包（含 ${n} 個音檔；${missing} 個音檔下載失敗）。`,
    saveFailed: (msg) => `儲存失敗：${msg}`,
    profileUnavailable: "風格設定檔不可用。",
    profileRules: "規則",
    profileFeatures: "特徵",
    profileSyllable: "音節槽位",
    profileSyllableCount: "音節數",
    profileCost: "成本",
    profileTags: "標籤",
    canonicalHeader: (label) => `Canonical（${label}）`,
    candidatesHeader: (label) => `表層音候選（${label}）`,
    phoneticHeader: (label) => `發音細節（${label}）`,
    observedHeader: (label) => `音訊辨識（${label}）`,
    profileHelpPrefix: "說明：",
    profileDefaultDesc: "使用風格設定來排序發音細節候選。",
    profileRecommendedTag: "此風格推薦",
    savedDefaultTag: "目前預設",
    noLessonAvailable: "沒有可用課程",
    switchLessonConfirm: "目前有未儲存變更，切換課程會遺失。確定切換？",
    runKindTest: "測試",
    runKindProduction: "正式",
    runKindLocal: "本機",
    runKindRemote: "線上",
    runKindCustom: "自訂",
    remoteLessonLabel: "線上課程",
    remoteLessonSelectPlaceholder: "請選擇課程…",
    remoteLessonLoaded: (name, count) => `已載入線上課程：${name}（${count} 句）`,
    remoteLessonLoadFailed: (msg) => `線上課程載入失敗：${msg}`,
    remoteLessonCatalogUnavailable: "無法取得線上課程目錄（離線或尚未上架）。",
    remoteSavedInBrowser: "已存到瀏覽器",
    savingToBrowser: "儲存中…",
    remoteSavedRestored: "（含本機編輯）",
    clearRemoteEdits: "清除本機編輯",
    entryHeading: "選擇課程",
    entryLoadBtn: "載入",
    entryOrLabel: "或",
    changeLessonBtn: "換課程",
  },
  en: {
    appTitle: "跟讀小助手",
    loadingLesson: "Loading lesson...",
    languageLabel: "UI Language",
    lessonSelectLabel: "Lesson",
    localLessonLabel: "Local Lesson (Offline)",
    localLessonHint: "Select a folder containing lesson.json and sentences/.",
    localLessonIdle: "Load a local lesson folder here. No account and no upload required.",
    localLessonAwaitImport: "Please load a local lesson folder first.",
    localLessonLoaded: (name, count) => `Local lesson loaded: ${name} (${count} sentences)`,
    localLessonLoadFailed: (msg) => `Failed to load local lesson: ${msg}`,
    localLessonNoFiles: "No files selected.",
    localLessonNoLessonJson: "lesson.json not found. Please select a single run folder.",
    localLessonMultipleLessonJson: "Multiple lesson.json files found. Please select a single run folder.",
    localLessonTooManyFiles: (n) => `Too many files (>${n}). Please select a smaller folder.`,
    localLessonTooLarge: (gb) => `Folder size exceeds ${gb} GB. Please select a smaller folder.`,
    localLessonServerUnavailable: (msg) => `Server mode unavailable (${msg}). You can load a local lesson folder instead.`,
    sentenceLabel: "Sentence",
    prev: "Prev",
    next: "Next",
    displaySystemLabel: "Display System",
    loopSentence: "Loop Current Sentence",
    loopGapLabel: "Loop Gap (sec)",
    loopCountLabel: "Loop Count (total plays, blank = infinite)",
    audioOffsetLabel: "Sentence Playback Range Offset",
    audioOffsetHelp: (limit) => `Adjust per-sentence start/end offsets (seconds), range ±${limit}s.`,
    audioStartOffset: "Start Offset",
    audioEndOffset: "End Offset",
    audioOffsetMinus: (step) => `-${step}s`,
    audioOffsetPlus: (step) => `+${step}s`,
    audioOffsetReset: "Reset Offsets",
    audioEffectiveRange: (start, end) => `Effective Playback Range: ${start} - ${end}`,
    viewModeLabel: "Sentence View Mode",
    compactView: "Compact",
    detailedView: "Detailed",
    presentationView: "Presentation",
    presentationReturn: "Back to Compact",
    presentationPlay: "Play",
    presentationPause: "Pause",
    presentationPlayAll: "Play All",
    presentationStopAll: "Stop All",
    presentationPlayAllHint: "Play all sentences in sequence",
    presentationStopAllHint: "Stop sequence playback",
    presentationPhonemeLabel: (label) => `Phonemes (${label})`,
    presentationDisplayHint: "Display system",
    presentationLoopHintOn: "Loop: on",
    presentationLoopHintOff: "Loop: off",
    presentationGapHint: "Gap seconds",
    presentationCountHint: "Play count (blank=infinite)",
    presentationSpeedHint: (rateText) => `Playback speed: ${rateText} (Shortcut: [ / ])`,
    presentationPhonemeToggleOn: "Phoneme On",
    presentationPhonemeToggleOff: "Phoneme Off",
    presentationPhonemeToggleOnHint: "Hide phonemes (Shortcut: P)",
    presentationPhonemeToggleOffHint: "Show phonemes (Shortcut: P)",
    presentationPrevHint: "Previous sentence",
    presentationNextHint: "Next sentence",
    downloadLessonJson: "Download lesson JSON",
    downloadOfflineZip: "Download Offline Package (ZIP)",
    compactNoticeIdle: "Compact edits are local-only. Download a lesson package to keep changes; closing the page will lose them.",
    compactNoticeUnsaved: "Compact edits are not downloaded yet. Download a lesson package before leaving this page.",
    compactNoticeDownloaded: "Compact edits downloaded.",
    compactSavedInBrowser: "Compact edits are local-only and are not saved to server lesson.",
    compactDownloadFailed: (msg) => `Download failed: ${msg}`,
    compactSwitchLessonConfirm: "Compact edits are not downloaded. Switching lessons will discard them. Continue?",
    keyboardLabel: "Phoneme Keyboard",
    keyboardHelp: "Click a symbol to insert into the active Gold field.",
    keyboardNoFocus: "Click a Gold field first.",
    phoneticProfileLabel: "Phonetic Profile",
    applyProfileSentence: "Apply Profile to Sentence",
    transcriptLabel: "Transcript (one sentence per line)",
    saveTranscript: "Save Transcript",
    buildCommand: "Generate Rebuild Command",
    rebuildCommandIdle: "Rebuild command is not generated yet.",
    rebuildCommandLoading: "Generating rebuild command...",
    rebuildCommandReady: (outDir) => `Rebuild command ready. Output will be: ${outDir}`,
    rebuildCommandFailed: (msg) => `Failed to generate rebuild command: ${msg}`,
    rebuildCommandNeedSaveTranscript: "Please save transcript edits before generating rebuild command.",
    rebuildCommandLocalUnavailable: "Local mode does not provide rebuild commands.",
    transcriptLoading: "Loading transcript...",
    transcriptUnavailable: "Transcript unavailable.",
    transcriptReady: (n) => `Transcript loaded, ${n} lines.`,
    transcriptSaved: (path) => `Transcript saved: ${path}`,
    transcriptSavedWithBackup: (path, backup) => `Transcript saved: ${path} (backup: ${backup})`,
    transcriptNeedRebuild: "Note: transcript is updated, but current lesson is not rebuilt yet.",
    transcriptSaveFailed: (msg) => `Transcript save failed: ${msg}`,
    transcriptLocalUnavailable: "Local mode cannot write transcript back. Download offline package to keep edits.",
    transcriptSourcePath: (path) => `Source: ${path}`,
    transcriptSavePath: (path) => `Save: ${path}`,
    transcriptContentFromLesson: "Current content source: lesson sentence text (first-time seed).",
    transcriptContentFromSource: "Current content source: original/existing transcript file.",
    transcriptUnsaved: "Transcript has unsaved changes.",
    switchLessonTranscriptConfirm: "Transcript has unsaved changes. Switching lessons will discard them. Continue?",
    showDetails: "Show Details",
    nonIpaGoldEdited: "Gold edits in non-IPA display are local-only and can be kept via lesson download.",
    nonIpaGoldSaveSkipped: "IPA Gold saved; non-IPA display edits are kept in downloadable lesson only.",
    saveGoldEdits: "Save Gold Edits",
    noUnsaved: "No unsaved changes.",
    quickFillLabel: "Quick Fill",
    quickFillPlaceholder: "Select source...",
    quickFillObserved: "Observed IPA",
    quickFillTeaching: "Teaching candidate",
    quickFillBestSurface: "Best surface candidate",
    quickFillCanonical: "Canonical",
    quickFillPhonetic: (n) => `Phonetic candidate ${n}`,
    quickFillSurface: (n) => `Surface candidate ${n}`,
    sentenceTitle: "Sentence",
    wordHeader: "Word",
    goldHeader: "Gold IPA (editable)",
    compactGoldHeader: (label) => `Gold (${label}, editable)`,
    notesHeader: "Notes",
    noSentenceFilter: "No sentences in current filter",
    noSentence: "No sentence",
    noSentenceMessage: "No sentence in current filter.",
    rangeText: (start, end) => `Range: ${start} - ${end}`,
    alignmentText: (pct) => `Alignment: ${pct}%`,
    displayText: (label, text) => `${label}: ${text}`,
    unsavedChanges: "Unsaved changes.",
    profileAppliedChanged: (n, sid) => `Profile applied: ${n} words updated in ${sid} (unsaved)`,
    profileAppliedNoChange: (sid) => `Profile applied: no changes in ${sid}`,
    savedWithBackup: (backup) => `Saved. Backup: ${backup}`,
    localSavedByDownload: "Local mode: download offline package to keep edits.",
    localSavedDownloaded: "Local mode: lesson JSON downloaded.",
    localSavedDownloadedZip: (n) => `Local mode: offline package downloaded (${n} audio files).`,
    savedDownloadedZip: (n) => `Offline package downloaded (${n} audio files).`,
    savedDownloadedZipWithMissing: (n, missing) => `Offline package downloaded (${n} audio files; ${missing} failed to download).`,
    saveFailed: (msg) => `Save failed: ${msg}`,
    profileUnavailable: "Profile config unavailable.",
    profileRules: "rules",
    profileFeatures: "features",
    profileSyllable: "syllable slots",
    profileSyllableCount: "syllables",
    profileCost: "cost",
    profileTags: "tags",
    canonicalHeader: (label) => `Canonical (${label})`,
    candidatesHeader: (label) => `Surface Candidates (${label})`,
    phoneticHeader: (label) => `Phonetic Detail (${label})`,
    observedHeader: (label) => `Observed (${label})`,
    profileHelpPrefix: "Description:",
    profileDefaultDesc: "Use profile to prioritize phonetic detail candidates.",
    profileRecommendedTag: "profile recommended",
    savedDefaultTag: "saved default",
    noLessonAvailable: "No lesson available",
    switchLessonConfirm: "You have unsaved changes. Switching lessons will discard them. Continue?",
    runKindTest: "test",
    runKindProduction: "production",
    runKindLocal: "local",
    runKindRemote: "online",
    runKindCustom: "custom",
    remoteLessonLabel: "Online Lessons",
    remoteLessonSelectPlaceholder: "Select a lesson…",
    remoteLessonLoaded: (name, count) => `Online lesson loaded: ${name} (${count} sentences)`,
    remoteLessonLoadFailed: (msg) => `Failed to load online lesson: ${msg}`,
    remoteLessonCatalogUnavailable: "Online lesson catalog unavailable (offline or not yet published).",
    remoteSavedInBrowser: "Saved in browser",
    savingToBrowser: "Saving…",
    remoteSavedRestored: "(with local edits)",
    clearRemoteEdits: "Clear local edits",
    entryHeading: "Select a Lesson",
    entryLoadBtn: "Load",
    entryOrLabel: "or",
    changeLessonBtn: "Change Lesson",
  },
};
